config/routes.rb
Rails.application.routes.draw do
 get "log_out" => "sessions#destroy", :as => "log_out"
 get "log_in"=>'sessions#new',as:"log_in"

   get  "sign_up"=>"users#new", as:"sign_up"
   root to:'sessions#new'
   resources :users
   post 'auth' => 'sessions#create'
   get  'auth'=> 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password
before_save :password_encrypt
#validation need to follow https://www.owasp.org/index.php/Authentication_Cheat_Sheet PENDING 
validates_presence_of :email, :password,:password_confirmation,message:"can't be blank"
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
validates_confirmation_of :password, message:"password and password confirmation do not match "
validates_uniqueness_of :email,message:"this email already exist"

#Password Hashed and salted  Can use has_secure_password for rails 4.1 
def password_encrypt
    if password.present?
      self.password_salt=BCrypt::Engine.generate_salt
      self.password_hash=BCrypt::Engine.hash_secret(password, password_salt)
    end
end
 def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
 end

#self.id  can be recovered from hashed and signed token on subsequent request,can be used in subsequent request
 def generate_auth_token
    payload = { user_id: self.id }
      AuthToken.encode(payload)
 end
   
end

app/controllers/application_controller.rb
class AuthToken
  def self.encode(payload, exp=24.hours.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, Rails.application.secrets.secret_key_base)
  end
  def self.decode(token)
    payload = JWT.decode(token, Rails.application.secrets.secret_key_base)[0]
    DecodedAuthToken.new(payload)
  rescue
    nil # It will raise an error if it is not a token that was generated with our secret key or if the user changes the contents of the payload
  end
end

class NotAuthenticatedError < StandardError
end
class AuthenticationTimeoutError < StandardError
end


# We could just return the payload as a hash, but having keys with indifferent access is always nice, plus we get an expired? method that will be useful later
class DecodedAuthToken < HashWithIndifferentAccess
  def expired?
    self[:exp] <= Time.now.to_i
  end
end


class ApplicationController < ActionController::Base
before_action :set_current_user, :authenticate_request
  rescue_from NotAuthenticatedError do
    render json: { error: 'Not Authorized' }, status: :unauthorized
  end
  rescue_from AuthenticationTimeoutError do
    render json: { error: 'Auth token is expired' }, status: 419 # unofficial timeout status code
  end
private
def set_current_user
    @current_user
    if decoded_auth_token
      @current_user ||= User.find(decoded_auth_token[:user_id])
    end
end
 def authenticate_request
    if auth_token_expired?
      fail AuthenticationTimeoutError
    elsif !@current_user
      fail NotAuthenticatedError
    end
 end

  def decoded_auth_token
    @decoded_auth_token ||= AuthToken.decode(http_auth_header_content)
  end

  def auth_token_expired?
    decoded_auth_token && decoded_auth_token.expired?
  end

  # JSON web token should be in authorization  token
  def http_auth_header_content
    return @http_auth_header_content if defined? @http_auth_header_content
    @http_auth_header_content = begin
      if request.headers['Authorization'].present?
        request.headers['Authorization'].split(' ').last
      else
        nil
      end
    end
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    helper_method :set_current_user
     skip_before_action :authenticate_request # this will be implemented later

  def new

  end
def create
  user = User.authenticate(params[:email], params[:password])
  if user
   render json: { auth_token: user.generate_auth_token }
  else
    render json: { error: 'Invalid username or password' }, status: :unauthorized
  end
end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :set_current_user
  skip_before_action :authenticate_request 
  def new
      @user=User.new
  end
  def create
      @user=User.new(user_params)
      if @user.save
          redirect_to root_url, notice:"Signed up"
      else
          render "new"
      end
  end
 
  private
  def user_params
      params.require(:user).permit(:email,:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if set_current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>